<?php

namespace AppBundle\Entities;

/**
 * BaseArray
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseArray extends \Doctrine\ORM\EntityRepository
{
}
