<?php

namespace AppBundle\Entities;

/**
 * BaseUsersGroupsPermissions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUsersGroupsPermissions extends \Doctrine\ORM\EntityRepository
{
}
