<?php

namespace AppBundle\Entities;

/**
 * BaseUser
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUser extends \Doctrine\ORM\EntityRepository
{
}
