<?php

namespace AppBundle\Entities;

/**
 * BaseSecurityAttempt
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseSecurityAttempt extends \Doctrine\ORM\EntityRepository
{
}
