<?php

namespace AppBundle\Entities;

/**
 * BaseUsersGroups
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUsersGroups extends \Doctrine\ORM\EntityRepository
{
}
