<?php

namespace AppBundle\Entities;

/**
 * BaseUserArray
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUserArray extends \Doctrine\ORM\EntityRepository
{
}
