<?php

namespace AppBundle\Entities;

/**
 * BaseSecuritySession
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseSecuritySession extends \Doctrine\ORM\EntityRepository
{
}
