<?php

namespace AppBundle\Entities;

/**
 * BaseLanguage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseLanguage extends \Doctrine\ORM\EntityRepository
{
}
