<?php

namespace AppBundle\Entities;

/**
 * BaseSecurityIp
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseSecurityIp extends \Doctrine\ORM\EntityRepository
{
}
