<?php

namespace AppBundle\Entities;

/**
 * BaseModule
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseModule extends \Doctrine\ORM\EntityRepository
{
}
