<?php

namespace AppBundle\Entities;

/**
 * BaseUsersSellers
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUsersSellers extends \Doctrine\ORM\EntityRepository
{
}
