<?php

namespace AppBundle\Entities;

/**
 * BaseUsersPermissions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUsersPermissions extends \Doctrine\ORM\EntityRepository
{
}
