<?php

namespace AppBundle\Entities;

/**
 * BaseSecurityTrack
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseSecurityTrack extends \Doctrine\ORM\EntityRepository
{
}
