<?php

namespace AppBundle\Entities;

/**
 * BaseLanguageLang
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseLanguageLang extends \Doctrine\ORM\EntityRepository
{
}
