<?php

namespace AppBundle\Entities;

/**
 * BaseArrayLang
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseArrayLang extends \Doctrine\ORM\EntityRepository
{
}
