<?php

namespace AppBundle\Entities;

/**
 * BaseSecurityCsrf
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseSecurityCsrf extends \Doctrine\ORM\EntityRepository
{
}
