<?php

namespace AppBundle\Repository;

/**
 * AppActivity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppActivity extends \Doctrine\ORM\EntityRepository
{
}
